export type CountryType = {
  country: string;
  code: string;
  capital: string;
  continent: string;
  flag: string;
};

export default class CountryData {
  public static countries = [
    {
      country: 'France',
      code: 'FR',
      capital: 'Paris',
      continent: 'Europe',
      flag: '🇫🇷',
    },
    {
      country: 'Belgique',
      code: 'BE',
      capital: 'Bruxelles',
      continent: 'Europe',
      flag: '🇧🇪',
    },
    {
      country: 'Suisse',
      code: 'CH',
      capital: 'Berne',
      continent: 'Europe',
      flag: '🇨🇭',
    },
    {
      country: 'Afghanistan',
      code: 'AF',
      capital: 'Kaboul',
      continent: 'Asie',
      flag: '🇦🇫',
    },
    {
      country: 'Afrique du Sud',
      code: 'ZA',
      capital: 'Pretoria',
      continent: 'Afrique',
      flag: '🇿🇦',
    },
    {
      country: 'Albanie',
      code: 'AL',
      capital: 'Tirana',
      continent: 'Europe',
      flag: '🇦🇱',
    },
    {
      country: 'Algérie',
      code: 'DZ',
      capital: 'Alger',
      continent: 'Afrique',
      flag: '🇩🇿',
    },
    {
      country: 'Allemagne',
      code: 'DE',
      capital: 'Berlin',
      continent: 'Europe',
      flag: '🇩🇪',
    },
    {
      country: 'Andorre',
      code: 'AD',
      capital: 'Andorre-la-Vieille',
      continent: 'Europe',
      flag: '🇦🇩',
    },
    {
      country: 'Angola',
      code: 'AO',
      capital: 'Luanda',
      continent: 'Afrique',
      flag: '🇦🇴',
    },
    {
      country: 'Antigua-et-Barbuda',
      code: 'AG',
      capital: 'Saint John\'s',
      continent: 'Amérique',
      flag: '🇦🇬',
    },
    {
      country: 'Arabie saoudite',
      code: 'SA',
      capital: 'Riyad',
      continent: 'Asie',
      flag: '🇸🇦',
    },
    {
      country: 'Argentine',
      code: 'AR',
      capital: 'Buenos Aires',
      continent: 'Amérique',
      flag: '🇦🇷',
    },
    {
      country: 'Arménie',
      code: 'AM',
      capital: 'Erevan',
      continent: 'Asie',
      flag: '🇦🇲',
    },
    {
      country: 'Australie',
      code: 'AU',
      capital: 'Canberra',
      continent: 'Océanie',
      flag: '🇦🇺',
    },
    {
      country: 'Autriche',
      code: 'AT',
      capital: 'Vienne',
      continent: 'Europe',
      flag: '🇦🇹',
    },
    {
      country: 'Azerbaïdjan',
      code: 'AZ',
      capital: 'Bakou',
      continent: 'Asie',
      flag: '🇦🇿',
    },
    {
      country: 'Bahamas',
      code: 'BS',
      capital: 'Nassau',
      continent: 'Amérique',
      flag: '🇧🇸',
    },
    {
      country: 'Bahreïn',
      code: 'BH',
      capital: 'Manama',
      continent: 'Asie',
      flag: '🇧🇭',
    },
    {
      country: 'Bangladesh',
      code: 'BD',
      capital: 'Dacca',
      continent: 'Asie',
      flag: '🇧🇩',
    },
    {
      country: 'Barbade',
      code: 'BB',
      capital: 'Bridgetown',
      continent: 'Amérique',
      flag: '🇧🇧',
    },

    {
      country: 'Belize',
      code: 'BZ',
      capital: 'Belmopan',
      continent: 'Amérique',
      flag: '🇧🇿',
    },
    {
      country: 'Bénin',
      code: 'BJ',
      capital: 'Porto-Novo',
      continent: 'Afrique',
      flag: '🇧🇯',
    },
    {
      country: 'Bhoutan',
      code: 'BT',
      capital: 'Thimphou',
      continent: 'Asie',
      flag: '🇧🇹',
    },
    {
      country: 'Biélorussie',
      code: 'BY',
      capital: 'Minsk',
      continent: 'Europe',
      flag: '🇧🇾',
    },
    {
      country: 'Birmanie',
      code: 'MM',
      capital: 'Naypyidaw',
      continent: 'Asie',
      flag: '🇲🇲',
    },
    {
      country: 'Bolivie',
      code: 'BO',
      capital: 'La Paz',
      continent: 'Amérique',
      flag: '🇧🇴',
    },
    {
      country: 'Bosnie-Herzégovine',
      code: 'BA',
      capital: 'Sarajevo',
      continent: 'Europe',
      flag: '🇧🇦',
    },
    {
      country: 'Botswana',
      code: 'BW',
      capital: 'Gaborone',
      continent: 'Afrique',
      flag: '🇧🇼',
    },
    {
      country: 'Brésil',
      code: 'BR',
      capital: 'Brasilia',
      continent: 'Amérique',
      flag: '🇧🇷',
    },
    {
      country: 'Brunei',
      code: 'BN',
      capital: 'Bandar Seri Begawan',
      continent: 'Asie',
      flag: '🇧🇳',
    },
    {
      country: 'Bulgarie',
      code: 'BG',
      capital: 'Sofia',
      continent: 'Europe',
      flag: '🇧🇬',
    },
    {
      country: 'Burkina Faso',
      code: 'BF',
      capital: 'Ouagadougou',
      continent: 'Afrique',
      flag: '🇧🇫',
    },
    {
      country: 'Burundi',
      code: 'BI',
      capital: 'Bujumbura',
      continent: 'Afrique',
      flag: '🇧🇮',
    },
    {
      country: 'Cambodge',
      code: 'KH',
      capital: 'Phnom Penh',
      continent: 'Asie',
      flag: '🇰🇭',
    },
    {
      country: 'Cameroun',
      code: 'CM',
      capital: 'Yaoundé',
      continent: 'Afrique',
      flag: '🇨🇲',
    },
    {
      country: 'Canada',
      code: 'CA',
      capital: 'Ottawa',
      continent: 'Amérique',
      flag: '🇨🇦',
    },
    {
      country: 'Cap-Vert',
      code: 'CV',
      capital: 'Praia',
      continent: 'Afrique',
      flag: '🇨🇻',
    },
    {
      country: 'Centrafrique',
      code: 'CF',
      capital: 'Bangui',
      continent: 'Afrique',
      flag: '🇨🇫',
    },
    {
      country: 'Chili',
      code: 'CL',
      capital: 'Santiago',
      continent: 'Amérique',
      flag: '🇨🇱',
    },
    {
      country: 'Chine',
      code: 'CN',
      capital: 'Pékin',
      continent: 'Asie',
      flag: '🇨🇳',
    },
    {
      country: 'Chypre',
      code: 'CY',
      capital: 'Nicosie',
      continent: 'Europe',
      flag: '🇨🇾',
    },
    {
      country: 'Cité du Vatican',
      code: 'VA',
      capital: 'Cité du Vatican',
      continent: 'Europe',
      flag: '🇻🇦',
    },
    {
      country: 'Colombie',
      code: 'CO',
      capital: 'Bogota',
      continent: 'Amérique',
      flag: '🇨🇴',
    },
    {
      country: 'Comores',
      code: 'KM',
      capital: 'Moroni',
      continent: 'Afrique',
      flag: '🇰🇲',
    },
    {
      country: 'Congo (République démocratique du)',
      code: 'CD',
      capital: 'Kinshasa',
      continent: 'Afrique',
      flag: '🇨🇩',
    },
    {
      country: 'Congo (République du)',
      code: 'CG',
      capital: 'Brazzaville',
      continent: 'Afrique',
      flag: '🇨🇬',
    },
    {
      country: 'Corée du Nord',
      code: 'KP',
      capital: 'Pyongyang',
      continent: 'Asie',
      flag: '🇰🇵',
    },
    {
      country: 'Corée du Sud',
      code: 'KR',
      capital: 'Séoul',
      continent: 'Asie',
      flag: '🇰🇷',
    },
    {
      country: 'Costa Rica',
      code: 'CR',
      capital: 'San José',
      continent: 'Amérique',
      flag: '🇨🇷',
    },
    {
      country: 'Côte d\'Ivoire',
      code: 'CI',
      capital: 'Yamoussoukro',
      continent: 'Afrique',
      flag: '🇨🇮',
    },
    {
      country: 'Croatie',
      code: 'HR',
      capital: 'Zagreb',
      continent: 'Europe',
      flag: '🇭🇷',
    },
    {
      country: 'Cuba',
      code: 'CU',
      capital: 'La Havane',
      continent: 'Amérique',
      flag: '🇨🇺',
    },
    {
      country: 'Danemark',
      code: 'DK',
      capital: 'Copenhague',
      continent: 'Europe',
      flag: '🇩🇰',
    },
    {
      country: 'Djibouti',
      code: 'DJ',
      capital: 'Djibouti',
      continent: 'Afrique',
      flag: '🇩🇯',
    },
    {
      country: 'Dominique',
      code: 'DM',
      capital: 'Roseau',
      continent: 'Amérique',
      flag: '🇩🇲',
    },
    {
      country: 'Égypte',
      code: 'EG',
      capital: 'Le Caire',
      continent: 'Afrique',
      flag: '🇪🇬',
    },
    {
      country: 'Émirats arabes unis',
      code: 'AE',
      capital: 'Abou Dabi',
      continent: 'Asie',
      flag: '🇦🇪',
    },
    {
      country: 'Équateur',
      code: 'EC',
      capital: 'Quito',
      continent: 'Amérique',
      flag: '🇪🇨',
    },
    {
      country: 'Érythrée',
      code: 'ER',
      capital: 'Asmara',
      continent: 'Afrique',
      flag: '🇪🇷',
    },
    {
      country: 'Espagne',
      code: 'ES',
      capital: 'Madrid',
      continent: 'Europe',
      flag: '🇪🇸',
    },

    {
      country: 'Estonie',
      code: 'EE',
      capital: 'Tallinn',
      continent: 'Europe',
      flag: '🇪🇪',
    },
    {
      country: 'États-Unis',
      code: 'US',
      capital: 'Washington, D.C.',
      continent: 'Amérique',
      flag: '🇺🇸',
    },
    {
      country: 'Éthiopie',
      code: 'ET',
      capital: 'Addis-Abeba',
      continent: 'Afrique',
      flag: '🇪🇹',
    },
    {
      country: 'Fidji',
      code: 'FJ',
      capital: 'Suva',
      continent: 'Océanie',
      flag: '🇫🇯',
    },
    {
      country: 'Finlande',
      code: 'FI',
      capital: 'Helsinki',
      continent: 'Europe',
      flag: '🇫🇮',
    },

    {
      country: 'Gabon',
      code: 'GA',
      capital: 'Libreville',
      continent: 'Afrique',
      flag: '🇬🇦',
    },
    {
      country: 'Gambie',
      code: 'GM',
      capital: 'Banjul',
      continent: 'Afrique',
      flag: '🇬🇲',
    },
    {
      country: 'Géorgie',
      code: 'GE',
      capital: 'Tbilissi',
      continent: 'Asie',
      flag: '🇬🇪',
    },
    {
      country: 'Ghana',
      code: 'GH',
      capital: 'Accra',
      continent: 'Afrique',
      flag: '🇬🇭',
    },
    {
      country: 'Grèce',
      code: 'GR',
      capital: 'Athènes',
      continent: 'Europe',
      flag: '🇬🇷',
    },
    {
      country: 'Grenade',
      code: 'GD',
      capital: 'St. George',
      continent: 'Amérique du Nord',
      flag: '🇬🇩',
    },
    {
      country: 'Guatemala',
      code: 'GT',
      capital: 'Guatemala City',
      continent: 'Amérique du Nord',
      flag: '🇬🇹',
    },
    {
      country: 'Guinée',
      code: 'GN',
      capital: 'Conakry',
      continent: 'Afrique',
      flag: '🇬🇳',
    },
    {
      country: 'Guinée-Bissau',
      code: 'GW',
      capital: 'Bissau',
      continent: 'Afrique',
      flag: '🇬🇼',
    },
    {
      country: 'Guyana',
      code: 'GY',
      capital: 'Georgetown',
      continent: 'Amérique du Sud',
      flag: '🇬🇾',
    },
    {
      country: 'Haïti',
      code: 'HT',
      capital: 'Port-au-Prince',
      continent: 'Amérique du Nord',
      flag: '🇭🇹',
    },
    {
      country: 'Honduras',
      code: 'HN',
      capital: 'Tegucigalpa',
      continent: 'Amérique du Nord',
      flag: '🇭🇳',
    },
    {
      country: 'Hongrie',
      code: 'HU',
      capital: 'Budapest',
      continent: 'Europe',
      flag: '🇭🇺',
    },
    {
      country: 'Islande',
      code: 'IS',
      capital: 'Reykjavik',
      continent: 'Europe',
      flag: '🇮🇸',
    },
    {
      country: 'Inde',
      code: 'IN',
      capital: 'New Delhi',
      continent: 'Asie',
      flag: '🇮🇳',
    },
    {
      country: 'Indonésie',
      code: 'ID',
      capital: 'Jakarta',
      continent: 'Asie',
      flag: '🇮🇩',
    },
    {
      country: 'Iran',
      code: 'IR',
      capital: 'Téhéran',
      continent: 'Asie',
      flag: '🇮🇷',
    },
    {
      country: 'Iraq',
      code: 'IQ',
      capital: 'Bagdad',
      continent: 'Asie',
      flag: '🇮🇶',
    },
    {
      country: 'Irlande',
      code: 'IE',
      capital: 'Dublin',
      continent: 'Europe',
      flag: '🇮🇪',
    },
    {
      country: 'Israël',
      code: 'IL',
      capital: 'Jérusalem',
      continent: 'Asie',
      flag: '🇮🇱',
    },
    {
      country: 'Italie',
      code: 'IT',
      capital: 'Rome',
      continent: 'Europe',
      flag: '🇮🇹',
    },
    {
      country: 'Jamaïque',
      code: 'JM',
      capital: 'Kingston',
      continent: 'Amérique du Nord',
      flag: '🇯🇲',
    },
    {
      country: 'Japon',
      code: 'JP',
      capital: 'Tokyo',
      continent: 'Asie',
      flag: '🇯🇵',
    },
    {
      country: 'Jordanie',
      code: 'JO',
      capital: 'Amman',
      continent: 'Asie',
      flag: '🇯🇴',
    },
    {
      country: 'Kazakhstan',
      code: 'KZ',
      capital: 'Nur-Sultan',
      continent: 'Asie',
      flag: '🇰🇿',
    },
    {
      country: 'Kenya',
      code: 'KE',
      capital: 'Nairobi',
      continent: 'Afrique',
      flag: '🇰🇪',
    },
    {
      country: 'Kiribati',
      code: 'KI',
      capital: 'Tarawa',
      continent: 'Océanie',
      flag: '🇰🇮',
    },
    {
      country: 'Koweït',
      code: 'KW',
      capital: 'Koweït',
      continent: 'Asie',
      flag: '🇰🇼',
    },
    {
      country: 'Kirghizistan',
      code: 'KG',
      capital: 'Bichkek',
      continent: 'Asie',
      flag: '🇰🇬',
    },
    {
      country: 'Laos',
      code: 'LA',
      capital: 'Vientiane',
      continent: 'Asie',
      flag: '🇱🇦',
    },
    {
      country: 'Lettonie',
      code: 'LV',
      capital: 'Riga',
      continent: 'Europe',
      flag: '🇱🇻',
    },
    {
      country: 'Liban',
      code: 'LB',
      capital: 'Beyrouth',
      continent: 'Asie',
      flag: '🇱🇧',
    },
    {
      country: 'Lesotho',
      code: 'LS',
      capital: 'Maseru',
      continent: 'Afrique',
      flag: '🇱🇸',
    },
    {
      country: 'Libéria',
      code: 'LR',
      capital: 'Monrovia',
      continent: 'Afrique',
      flag: '🇱🇷',
    },
    {
      country: 'Libye',
      code: 'LY',
      capital: 'Tripoli',
      continent: 'Afrique',
      flag: '🇱🇾',
    },
    {
      country: 'Liechtenstein',
      code: 'LI',
      capital: 'Vaduz',
      continent: 'Europe',
      flag: '🇱🇮',
    },
    {
      country: 'Lituanie',
      code: 'LT',
      capital: 'Vilnius',
      continent: 'Europe',
      flag: '🇱🇹',
    },
    {
      country: 'Luxembourg',
      code: 'LU',
      capital: 'Luxembourg',
      continent: 'Europe',
      flag: '🇱🇺',
    },
    {
      country: 'Macédoine du Nord',
      code: 'MK',
      capital: 'Skopje',
      continent: 'Europe',
      flag: '🇲🇰',
    },
    {
      country: 'Madagascar',
      code: 'MG',
      capital: 'Antananarivo',
      continent: 'Afrique',
      flag: '🇲🇬',
    },
    {
      country: 'Malawi',
      code: 'MW',
      capital: 'Lilongwe',
      continent: 'Afrique',
      flag: '🇲🇼',
    },
    {
      country: 'Malaisie',
      code: 'MY',
      capital: 'Kuala Lumpur',
      continent: 'Asie',
      flag: '🇲🇾',
    },
    {
      country: 'Maldives',
      code: 'MV',
      capital: 'Malé',
      continent: 'Asie',
      flag: '🇲🇻',
    },
    {
      country: 'Mali',
      code: 'ML',
      capital: 'Bamako',
      continent: 'Afrique',
      flag: '🇲🇱',
    },
    {
      country: 'Malte',
      code: 'MT',
      capital: 'La Valette',
      continent: 'Europe',
      flag: '🇲🇹',
    },
    {
      country: 'Îles Marshall',
      code: 'MH',
      capital: 'Majuro',
      continent: 'Océanie',
      flag: '🇲🇭',
    },
    {
      country: 'Mauritanie',
      code: 'MR',
      capital: 'Nouakchott',
      continent: 'Afrique',
      flag: '🇲🇷',
    },
    {
      country: 'Maurice',
      code: 'MU',
      capital: 'Port-Louis',
      continent: 'Afrique',
      flag: '🇲🇺',
    },
    {
      country: 'Mexique',
      code: 'MX',
      capital: 'Mexico',
      continent: 'Amérique du Nord',
      flag: '🇲🇽',
    },
    {
      country: 'Micronésie',
      code: 'FM',
      capital: 'Palikir',
      continent: 'Océanie',
      flag: '🇫🇲',
    },
    {
      country: 'Moldavie',
      code: 'MD',
      capital: 'Chisinau',
      continent: 'Europe',
      flag: '🇲🇩',
    },
    {
      country: 'Monaco',
      code: 'MC',
      capital: 'Monaco',
      continent: 'Europe',
      flag: '🇲🇨',
    },
    {
      country: 'Mongolie',
      code: 'MN',
      capital: 'Oulan-Bator',
      continent: 'Asie',
      flag: '🇲🇳',
    },
    {
      country: 'Monténégro',
      code: 'ME',
      capital: 'Podgorica',
      continent: 'Europe',
      flag: '🇲🇪',
    },
    {
      country: 'Maroc',
      code: 'MA',
      capital: 'Rabat',
      continent: 'Afrique',
      flag: '🇲🇦',
    },
    {
      country: 'Mozambique',
      code: 'MZ',
      capital: 'Maputo',
      continent: 'Afrique',
      flag: '🇲🇿',
    },
    {
      country: 'Myanmar',
      code: 'MM',
      capital: 'Naypyidaw',
      continent: 'Asie',
      flag: '🇲🇲',
    },
    {
      country: 'Namibie',
      code: 'NA',
      capital: 'Windhoek',
      continent: 'Afrique',
      flag: '🇳🇦',
    },
    {
      country: 'Nauru',
      code: 'NR',
      capital: 'Yaren',
      continent: 'Océanie',
      flag: '🇳🇷',
    },
    {
      country: 'Népal',
      code: 'NP',
      capital: 'Katmandou',
      continent: 'Asie',
      flag: '🇳🇵',
    },
    {
      country: 'country-Bas',
      code: 'NL',
      capital: 'Amsterdam',
      continent: 'Europe',
      flag: '🇳🇱',
    },
    {
      country: 'Nouvelle-Zélande',
      code: 'NZ',
      capital: 'Wellington',
      continent: 'Océanie',
      flag: '🇳🇿',
    },
    {
      country: 'Nicaragua',
      code: 'NI',
      capital: 'Managua',
      continent: 'Amérique du Nord',
      flag: '🇳🇮',
    },
    {
      country: 'Niger',
      code: 'NE',
      capital: 'Niamey',
      continent: 'Afrique',
      flag: '🇳🇪',
    },
    {
      country: 'Nigéria',
      code: 'NG',
      capital: 'Abuja',
      continent: 'Afrique',
      flag: '🇳🇬',
    },
    {
      country: 'Norvège',
      code: 'NO',
      capital: 'Oslo',
      continent: 'Europe',
      flag: '🇳🇴',
    },
    {
      country: 'Oman',
      code: 'OM',
      capital: 'Mascate',
      continent: 'Asie',
      flag: '🇴🇲',
    },
    {
      country: 'Pakistan',
      code: 'PK',
      capital: 'Islamabad',
      continent: 'Asie',
      flag: '🇵🇰',
    },
    {
      country: 'Palaos',
      code: 'PW',
      capital: 'Ngerulmud',
      continent: 'Océanie',
      flag: '🇵🇼',
    },
    {
      country: 'Panama',
      code: 'PA',
      capital: 'Panama Ville',
      continent: 'Amérique du Nord',
      flag: '🇵🇦',
    },
    {
      country: 'Papouasie-Nouvelle-Guinée',
      code: 'PG',
      capital: 'Port Moresby',
      continent: 'Océanie',
      flag: '🇵🇬',
    },
    {
      country: 'Paraguay',
      code: 'PY',
      capital: 'Asunción',
      continent: 'Amérique du Sud',
      flag: '🇵🇾',
    },
    {
      country: 'Pérou',
      code: 'PE',
      capital: 'Lima',
      continent: 'Amérique du Sud',
      flag: '🇵🇪',
    },
    {
      country: 'Philippines',
      code: 'PH',
      capital: 'Manille',
      continent: 'Asie',
      flag: '🇵🇭',
    },
    {
      country: 'Pologne',
      code: 'PL',
      capital: 'Varsovie',
      continent: 'Europe',
      flag: '🇵🇱',
    },
    {
      country: 'Portugal',
      code: 'PT',
      capital: 'Lisbonne',
      continent: 'Europe',
      flag: '🇵🇹',
    },
    {
      country: 'Qatar',
      code: 'QA',
      capital: 'Doha',
      continent: 'Asie',
      flag: '🇶🇦',
    },
    {
      country: 'Roumanie',
      code: 'RO',
      capital: 'Bucarest',
      continent: 'Europe',
      flag: '🇷🇴',
    },
    {
      country: 'Russie',
      code: 'RU',
      capital: 'Moscou',
      continent: 'Europe',
      flag: '🇷🇺',
    },
    {
      country: 'Rwanda',
      code: 'RW',
      capital: 'Kigali',
      continent: 'Afrique',
      flag: '🇷🇼',
    },
    {
      country: 'Saint-Christophe-et-Niévès',
      code: 'KN',
      capital: 'Basseterre',
      continent: 'Amérique du Nord',
      flag: '🇰🇳',
    },
    {
      country: 'Sainte-Lucie',
      code: 'LC',
      capital: 'Castries',
      continent: 'Amérique du Nord',
      flag: '🇱🇨',
    },
    {
      country: 'Saint-Vincent-et-les-Grenadines',
      code: 'VC',
      capital: 'Kingstown',
      continent: 'Amérique du Nord',
      flag: '🇻🇨',
    },
    {
      country: 'Samoa',
      code: 'WS',
      capital: 'Apia',
      continent: 'Océanie',
      flag: '🇼🇸',
    },
    {
      country: 'Saint-Marin',
      code: 'SM',
      capital: 'Saint-Marin',
      continent: 'Europe',
      flag: '🇸🇲',
    },
    {
      country: 'Sao Tomé-et-Principe',
      code: 'ST',
      capital: 'São Tomé',
      continent: 'Afrique',
      flag: '🇸🇹',
    },
    {
      country: 'Arabie Saoudite',
      code: 'SA',
      capital: 'Riyad',
      continent: 'Asie',
      flag: '🇸🇦',
    },
    {
      country: 'Sahara occidental',
      code: 'EH',
      capital: 'El Aaiún',
      continent: 'Afrique',
      flag: '🇪🇭',
    },
    {
      country: 'Sénégal',
      code: 'SN',
      capital: 'Dakar',
      continent: 'Afrique',
      flag: '🇸🇳',
    },
    {
      country: 'Serbie',
      code: 'RS',
      capital: 'Belgrade',
      continent: 'Europe',
      flag: '🇷🇸',
    },
    {
      country: 'Seychelles',
      code: 'SC',
      capital: 'Victoria',
      continent: 'Afrique',
      flag: '🇸🇨',
    },
    {
      country: 'Sierra Leone',
      code: 'SL',
      capital: 'Freetown',
      continent: 'Afrique',
      flag: '🇸🇱',
    },
    {
      country: 'Singapour',
      code: 'SG',
      capital: 'Singapour',
      continent: 'Asie',
      flag: '🇸🇬',
    },
    {
      country: 'Slovaquie',
      code: 'SK',
      capital: 'Bratislava',
      continent: 'Europe',
      flag: '🇸🇰',
    },
    {
      country: 'Slovénie',
      code: 'SI',
      capital: 'Ljubljana',
      continent: 'Europe',
      flag: '🇸🇮',
    },
    {
      country: 'Îles Salomon',
      code: 'SB',
      capital: 'Honiara',
      continent: 'Océanie',
      flag: '🇸🇧',
    },
    {
      country: 'Somalie',
      code: 'SO',
      capital: 'Mogadiscio',
      continent: 'Afrique',
      flag: '🇸🇴',
    },

    {
      country: 'Soudan du Sud',
      code: 'SS',
      capital: 'Djouba',
      continent: 'Afrique',
      flag: '🇸🇸',
    },
    {
      country: 'Sri Lanka',
      code: 'LK',
      capital: 'Colombo',
      continent: 'Asie',
      flag: '🇱🇰',
    },
    {
      country: 'Soudan',
      code: 'SD',
      capital: 'Khartoum',
      continent: 'Afrique',
      flag: '🇸🇩',
    },
    {
      country: 'Suriname',
      code: 'SR',
      capital: 'Paramaribo',
      continent: 'Amérique du Sud',
      flag: '🇸🇷',
    },
    {
      country: 'Eswatini',
      code: 'SZ',
      capital: 'Mbabane',
      continent: 'Afrique',
      flag: '🇸🇿',
    },
    {
      country: 'Suède',
      code: 'SE',
      capital: 'Stockholm',
      continent: 'Europe',
      flag: '🇸🇪',
    },

    {
      country: 'Syrie',
      code: 'SY',
      capital: 'Damas',
      continent: 'Asie',
      flag: '🇸🇾',
    },
    {
      country: 'Taïwan',
      code: 'TW',
      capital: 'Taipei',
      continent: 'Asie',
      flag: '🇹🇼',
    },
    {
      country: 'Tadjikistan',
      code: 'TJ',
      capital: 'Douchanbé',
      continent: 'Asie',
      flag: '🇹🇯',
    },
    {
      country: 'Tanzanie',
      code: 'TZ',
      capital: 'Dodoma',
      continent: 'Afrique',
      flag: '🇹🇿',
    },
    {
      country: 'Thaïlande',
      code: 'TH',
      capital: 'Bangkok',
      continent: 'Asie',
      flag: '🇹🇭',
    },
    {
      country: 'Timor oriental',
      code: 'TL',
      capital: 'Dili',
      continent: 'Asie',
      flag: '🇹🇱',
    },
    {
      country: 'Togo',
      code: 'TG',
      capital: 'Lomé',
      continent: 'Afrique',
      flag: '🇹🇬',
    },
    {
      country: 'Tonga',
      code: 'TO',
      capital: 'Nuku\'alofa',
      continent: 'Océanie',
      flag: '🇹🇴',
    },
    {
      country: 'Trinité-et-Tobago',
      code: 'TT',
      capital: 'Port-d\'Espagne',
      continent: 'Amérique du Nord',
      flag: '🇹🇹',
    },
    {
      country: 'Tunisie',
      code: 'TN',
      capital: 'Tunis',
      continent: 'Afrique',
      flag: '🇹🇳',
    },
    {
      country: 'Turquie',
      code: 'TR',
      capital: 'Ankara',
      continent: 'Asie',
      flag: '🇹🇷',
    },
    {
      country: 'Turkménistan',
      code: 'TM',
      capital: 'Achgabat',
      continent: 'Asie',
      flag: '🇹🇲',
    },
    {
      country: 'Tuvalu',
      code: 'TV',
      capital: 'Funafuti',
      continent: 'Océanie',
      flag: '🇹🇻',
    },
    {
      country: 'Ouganda',
      code: 'UG',
      capital: 'Kampala',
      continent: 'Afrique',
      flag: '🇺🇬',
    },
    {
      country: 'Ukraine',
      code: 'UA',
      capital: 'Kiev',
      continent: 'Europe',
      flag: '🇺🇦',
    },
    {
      country: 'Émirats arabes unis',
      code: 'AE',
      capital: 'Abou Dabi',
      continent: 'Asie',
      flag: '🇦🇪',
    },
    {
      country: 'Royaume-Uni',
      code: 'GB',
      capital: 'Londres',
      continent: 'Europe',
      flag: '🇬🇧',
    },
    {
      country: 'États-Unis',
      code: 'US',
      capital: 'Washington, D.C.',
      continent: 'Amérique du Nord',
      flag: '🇺🇸',
    },
    {
      country: 'Uruguay',
      code: 'UY',
      capital: 'Montevideo',
      continent: 'Amérique du Sud',
      flag: '🇺🇾',
    },
    {
      country: 'Ouzbékistan',
      code: 'UZ',
      capital: 'Tachkent',
      continent: 'Asie',
      flag: '🇺🇿',
    },
    {
      country: 'Vanuatu',
      code: 'VU',
      capital: 'Port-Vila',
      continent: 'Océanie',
      flag: '🇻🇺',
    },
    {
      country: 'Venezuela',
      code: 'VE',
      capital: 'Caracas',
      continent: 'Amérique du Sud',
      flag: '🇻🇪',
    },
    {
      country: 'Vietnam',
      code: 'VN',
      capital: 'Hanoï',
      continent: 'Asie',
      flag: '🇻🇳',
    },
    {
      country: 'Wallis et Futuna',
      code: 'WF',
      capital: 'Mata-Utu',
      continent: 'Océanie',
      flag: '🇼🇫',
    },

    {
      country: 'Yémen',
      code: 'YE',
      capital: 'Sanaa',
      continent: 'Asie',
      flag: '🇾🇪',
    },
    {
      country: 'Zambie',
      code: 'ZM',
      capital: 'Lusaka',
      continent: 'Afrique',
      flag: '🇿🇲',
    },
    {
      country: 'Zimbabwe',
      code: 'ZW',
      capital: 'Harare',
      continent: 'Afrique',
      flag: '🇿🇼',
    },
  ];
}
